#!/usr/bin/env bash

files="files.txt"
timestamp="timestamp.dummy"
touch $timestamp

while true; do
    for f in $(cat $files); do
        if [[ "../$f" -nt ${timestamp} ]]; then
           echo "$f has been updated... rebuilding"
           make -k bt
           touch $timestamp
           break;
        fi
    done
    sleep 2;
done
